name: streamlit-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas>=1.3.0
  - numpy>=1.20.0
  - pip
  - pip:
    - streamlit>=1.12.0
    - altair>=4.0.0
    - plotly>=5.0.0